algovisualizer/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account', include('users.urls') , name='users'),
    path('', include('home.urls') , name='home')
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('sorting/<str:algorithm>', views.sorting, name='sorting'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('/signup', views.signup_view, name='signup'),

    path('/login', views.login_view, name='login'),
    path('/logout', views.logout_view, name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

# Create your models here.

home/views.py
from django.shortcuts import render , redirect
import openai
from django.contrib.auth.decorators import login_required
openai.api_key = "YOU NEED TO ENTER YOUR OPEN AI KEY"
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import PythonLexer




#function to render home page only if user is logged in
@login_required(login_url='users:login')
def index(request):

    return render(request, 'home/index.html'  )


#function to present all the sorting algoritm
def sorting(request,algorithm):

    #requesting data after submitting the form
    if request.method == "POST":

        #getting user selected programming language
        programingLanguage = request.POST.get("option")

    else:
        programingLanguage = "python"


    #tokens for gpt3 model to generate text
    prompt = f"write simple {algorithm} algorithm in {programingLanguage} programing language with proper indentation"

    #requesting api to generate tokens using text-davinci-001 engine and given prompt message
    response = openai.Completion.create(engine="text-davinci-001" , prompt=prompt , max_tokens=1000 )

    #highlighting programing text data into actual code with proper indentation.
    highlighted_code = highlight(response['choices'][0]['text'], PythonLexer(), HtmlFormatter(style='friendly', linenos=True, noclasses=True))


    #context to pass the algorithm name from user input
    context = {'algorithmname':algorithm , "algorithmcode": highlighted_code , 'programinglanguage' : programingLanguage}
    return render(request, 'home/sorting.html' , context  )

users/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
import math , random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.contrib import messages



#returns main page of account which isn't developed yet
def index(request):
    return HttpResponse("Hello, world. You're at the pollasss index.")



#function to generate random otp
def generateOTP():
     digits = "0123456789"
     OTP = ""
     for i in range(4) :
         OTP += digits[math.floor(random.random() * 10)]
     return OTP


#function to send email to user entered email with generated otp
def sent_mail(request , email , genertated_otp):

    #html format
    htmlgen = f'<p>Your OTP is <strong>{genertated_otp}</strong></p>'

    #send email
    send_mail('Your requested OTP',genertated_otp,'AlgorithmVisualizer',[email], fail_silently=False, html_message=htmlgen)



#fucntion returns sign up page including signing up the new user
def signup_view(request):

    #if user submit the registraion form
    if request.method == "POST":

        #fetching user otp if otp form is submitted
        user_otp = request.POST.get("user-otp")
        if user_otp:

            #if otp for,is submitted then fetching genereted data from session
            generated_otp = request.session.get("generated_otp")

            #if user entered otp and generated otp is same then fetching email an password from session and saving the new user
            if(user_otp == generated_otp):
                email = request.session.get("email")
                password = request.session.get("password")


                user = User.objects.create_user(email , password = password )
                user.save()
                messages.success(request , message= "Successfully Created New User. Redirected to Login page." , extra_tags="bg-green-100 border border-green-400 text-black-700 px-4 py-3 rounded relative")

                return redirect('users:login')
            else:
                messages.error(request , message= "Wrong OTP" , extra_tags="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative")





        #fetching email and password from the registration form
        password= request.POST.get('user-password1')
        email= request.POST.get('user-email')

        request.session["email"] = email
        request.session["password"] = password

        #checking if user is already exist or not
        userexist = User.objects.filter( username = email ).exists()

        #if user does not exist then performing registering new user
        if userexist is False:

            #genereated otp
            generated_otp=generateOTP()

            #sending email with otp
            sent_mail(request , email , generated_otp)

            #storing generated otp in session
            request.session["generated_otp"] = generated_otp

            return render(request, 'users/verification.html'  )

        else:

            #if user is already exist then showing the error
            messages.error(request, {'title':'Email Already Exist','class':"bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" , 'heading':"Error" })


    context = {'otpverificationwindow' : "none" }
    return render(request, 'users/signup.html' , context )




#function to return login view page with login the given user
def login_view(request):


    #if user submit the login form
    if request.method == "POST":

        #fetchinng password and email from given user input
        password= request.POST.get('user-password1')
        email= request.POST.get('user-email')


        #checking if user is arleady exist or not
        userexist = User.objects.filter( username = email ).exists()

        #if user does not exist then showing error
        if userexist is False:

            messages.error(request , message= "Email is not Registered" , extra_tags="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative")

        else:

            #if user is exist and authentiation complete successfully then login the user and redireting user to home page
            user =  authenticate(request,username=email , password=password)

            if user is None:
                messages.error(request , message= "Password Does not match" , extra_tags="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative")
            else:
                login( request , user)
                messages.success(request , message= "Successfully Login with given credentials" , extra_tags="bg-green-100 border border-green-400 text-black-700 px-4 py-3 rounded relative")
                return redirect('home:index')


    #rendering login html page
    return render(request, 'users/login.html' )




#function to logout the user and redirectinng to login page
def logout_view(request):
    logout(request)
    return redirect('users:login')

home/templates/home/basic.html
<html lang="en">
    <head>
        {% load static %}

        <link
        href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
        rel="stylesheet"
        />
        <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;900&display=swap"
        rel="stylesheet"
        />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'home/css/style.css' %}" />
        <meta
        name="viewport"
        content="width=device-width,initial-scale=1,maximum-scale=1"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap CSS -->


    </head>



    <body class="body">


        <header class="site-navbar js-sticky-header site-navbar-target" role="banner">

          <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #a0aec0!important;">
            <a class="navbar-brand" href="/">Algo Visualizer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sorting Algorithm
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'home:sorting' 'bubbleSort' %}">Bubble Sort</a>
                    <a class="dropdown-item" href="{% url 'home:sorting' 'selectionSort' %}">Selection Sort</a>
                    <a class="dropdown-item" href="{% url 'home:sorting' 'insertionSort' %}">insertion Sort</a>
                    <a class="dropdown-item" href="{% url 'home:sorting' 'quickSort' %}">Quick Sort</a>
                    <a class="dropdown-item" href="{% url 'home:sorting' 'mergeSort' %}">Merge Sort</a>
                  </div>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#">Disabled</a>
                </li>

              </ul>

              <ul class="navbar-nav mr-auto" style="margin-right: 15px !important;">
                {%if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown username" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span id="username">{{user}}</span>
                  </a>
                  <div class="dropdown-menu" style="left: -150;" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Account</a>
                    <a class="dropdown-item" href="{% url 'users:login' %}">Login Another User</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                  </div>
                </li>
                {% else %}
                <a class="nav-link dropdown-toggle" href="{% url 'users:login' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Login
                </a>
                {%endif%}
              </ul>


            </div>
          </nav>


<div style="margin-top: 55px">
  {%if messages%}
                      {% for i in messages%}

                          <div class="alert" role ="alert" style="margin: auto;">
                              <div class="{{i.extra_tags}}" role="alert">
                                  <strong class="font-bold"></strong>
                                  <span class="block sm:inline">{{i.message}}</span>
                                  <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                                    <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
                                  </span>
                                </div>
                              <strong></strong>


                          </div>
                      {%endfor%}
          {%endif%}
</div>

    </header>


        {%block body %}{%endblock%}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script>
          var username  = document.getElementById("username").textContent

          var user  = username.substring(0, username.lastIndexOf("@"));
          document.getElementById("username").innerHTML = user
        </script>
        <script src="static/home/js/script.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'users/js/script.js' %}"></script>
            <script
        src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js"
        defer
        ></script>
    </body>
</html>

home/templates/home/sorting.html
{% include 'home/basic.html' %}

{%block body%}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sorting Visualizer</title>

</head>
<header>
    <hr>
    <div style="display: flex;">
        <h4 style="margin-left: 30px; "  align="center">{{algorithmname}} Visualizer</h4>
        <div class="col gap-2 d-sm-flex" id="newArray" style="justify-content: flex-end;">
            <button type="button" class="btn btn-outline-success btn-dark newArray">New Array</button>
        </div>
        <button type="button" class="btn btn-outline-primary btn-dark {{algorithmname}}">Visualize</button>
    </div>

    <hr>
    <nav>
        <div class="row">

            <div class="col" id="input">
                <span id="size">Size
                    <input id="arr_sz" type="range" min="5" max="100" step=1 value=60>
                </span>
                <span id="speed">Speed
                    <input id="speed_input" type="range" min="20" max="300" stepDown=10 value=60>
                </span>
            </div>
            <div class="col gap-2 d-sm-flex justify-content-end">
            </div>
        </div>
    </nav>
</header>
<body class="p-3 mb-2 bg-dark text-white">
    <h1 id="algorithmname" style="display: none;">
        {{algorithmname}}
    </h1>
    <div id="bars" class="flex-container"></div>
    <hr>
    <br>
    <div class="bg-black mb-4 rounded-md" style="margin: auto; width: 70%;">
        <div class="flex items-center relative text-gray-200 bg-gray-800 px-4 py-2 text-xs font-sans" style="display: block;">
            <span style="float: right;">
                <a href="{{ request.get_full_path }}">Reload to update</a>
            </span>
            <span >

                <form method="post" style="margin: 0;">
                    {% csrf_token %}
                    <select id="programmingdropdown" name="option" style="background: transparent !important;" onchange="this.form.submit();">
                        <option class="Option" name="option" value="python" >Python</option>
                        <option class="Option" name="option" value="c++" >C++</option>
                        <option class="Option" name="option" value="java " >Java</option>
                        <option class="Option" name="option" value="php" >php</option>
                        <option class="Option" name="option" value="javascript" >Jaavascript</option>
                        <option class="Option" name="option" value="ruby" >ruby</option>
                        <option class="Option" name="option" value="r" >r</option>
                        <option class="Option" name="option" value="powershell" >powershell</option>
                      </select>
                </form>
            </span>
            <p class="programinglanguage" style="display: none;">{{programinglanguage}}  </p>
            <style>
                .Option{
                    background: black;
                }
            </style>

        </div>
        <div class="p-4 overflow-y-auto" style="color: white; background: white; padding: 0rem!important;">
            {{algorithmcode |safe}}
            <code class="!whitespace-pre hljs language-python"></code>
        </div>


    </div>
    <script>
        var select = document.getElementById("programmingdropdown");
        var targetValue  = "{{programinglanguage}}";

        for (var i = 0; i < select.options.length; i++) {
            if ((select.options[i].value).replace(/\s+/g, '') === (targetValue)) {
            // Set the selected property to true for the matching option
            select.options[i].selected = true;
            break;
            }
        }

    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="{% static 'home/js/sorting.js' %}"></script>
    <script src="{% static 'home/js/bubble.js' %}"></script>
    <script src="{% static 'home/js/selection.js' %}"></script>
    <script src="{% static 'home/js/merge.js' %}"></script>
    <script src="{% static 'home/js/quick.js' %}"></script>
    <script src="{% static 'home/js/insertion.js' %}"></script>
    <script>

    </script>
</body>
</html>


{% endblock %}

users/templates/users/basic.html
<html lang="en">
    <head>
        {% load static %}
        <script src="{% static 'users/js/script.js' %}"></script>
        <link rel="stylesheet" href="{% static 'users/css/style.css' %}" />
        <link
        href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
        rel="stylesheet"
        />
        <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;900&display=swap"
        rel="stylesheet"
        />
        <meta
        name="viewport"
        content="width=device-width,initial-scale=1,maximum-scale=1"
        />

         <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->


    </head>



    <body class="min-h-screen bg-gray-100 text-gray-900 flex justify-center">


        {%block body %}{%endblock%}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->

            <script
        src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js"
        defer
        ></script>
    </body>
</html>

users/templates/users/login.html
  {% include 'users/basic.html' %}

  {%block body%}
  {% load static %}
  <div
  class="max-w-screen-xl m-0 sm:m-20 bg-white shadow sm:rounded-lg flex justify-center flex-1"
  style="margin: 3rem;"
  >
    <div class="lg:w-1/2 xl:w-5/12 p-6 sm:p-12" style="padding: 0rem;">


      {%if messages%}
        {% for i in messages%}

          <div class="alert" role ="alert" style="margin: auto;">
            <div class="{{i.extra_tags}}" role="alert">
              <strong class="font-bold"></strong>
              <span class="block sm:inline">{{i.message}}</span>
              <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
              </span>
            </div>
          </div>
        {%endfor%}
      {%endif%}

      <div class="mt-12 flex flex-col items-center" style="margin-top: 9rem;">



        <h1 class="text-2xl xl:text-3xl font-extrabold"">
          Sign In
        </h1>
        <div class="w-full flex-1 mt-8">


          <div class="my-12 border-b text-center" style="margin-top: 0rem;">
            <div
              class="leading-none px-2 inline-block text-sm text-gray-600 tracking-wide font-medium bg-white transform translate-y-1/2"
            >
              sign In with e-mail
            </div>
          </div>
          <div class="mx-auto max-w-xs">
            <form action="" method="POST">
              {% csrf_token %}

                <input
                  class="w-full px-8 py-3 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white"
                  type="email"
                  name="user-email"
                  placeholder="Email"
                  required/>
                <input
                  class="w-full px-8 py-3 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white mt-5"
                  id="login-password" type="password" name="user-password1" placeholder="Password"
                  required/>
                {{form.errors}}
                <button
                  class="mt-5 tracking-wide font-semibold bg-indigo-500 text-gray-100 w-full py-3 rounded-lg hover:bg-indigo-700 transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none"
                >
                  <svg
                    class="w-6 h-6 -ml-2"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M16 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" />
                    <circle cx="8.5" cy="7" r="4" />
                    <path d="M20 8v6M23 11h-6" />
                  </svg>
                  <span class="ml-3">
                    Sign In
                  </span>
                </button>
            </form>
            <br>
            <hr style="width: 100%; height: 2px; background-color: black;">
            <br>
            <a href="{% url 'users:signup' %}"> Sign Up </a>
            <p class="mt-6 text-xs text-gray-600 text-center">
              I agree
              <a href="#" class="border-b border-gray-500 border-dotted">
                Terms of Service
              </a>
              and its
              <a href="#" class="border-b border-gray-500 border-dotted">
                Privacy Policy
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="flex-1 bg-indigo-100 text-center hidden lg:flex">
      <div
        class="m-12 xl:m-16 w-full bg-contain bg-center bg-no-repeat"
        style="background-image: url('https://storage.googleapis.com/devitary-image-host.appspot.com/15848031292911696601-undraw_designer_life_w96d.svg');"
      ></div>
    </div>
  </div>
  <script>
    function removediv(){
    document.getElementById("headeralert").style.display = "none";
    }

  </script>
        {% endblock %}

users/templates/users/signup.html
{% include 'users/basic.html' %}

{%block body%}
{% load static %}
      <div
        class="max-w-screen-xl m-0 sm:m-20 bg-white shadow sm:rounded-lg flex justify-center flex-1"
        style="margin: 3rem;"
      >
        <div class="lg:w-1/2 xl:w-5/12 p-6 sm:p-12" style="padding: 0rem; ">


          {%if messages%}
                      {% for i in messages%}
                          <div id="headeralert" class="alert {{i.extra_tags}}" role ="alert" style="margin: auto;">
                              <div class="{{i.message.class}}" role="alert">
                                  <strong class="font-bold">{{i.message.heading}}</strong>
                                  <span class="block sm:inline">{{i.message.title}}</span>
                                  <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                                    <svg onclick="removediv()" class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
                                  </span>
                                </div>
                              <strong></strong>


                          </div>
                      {%endfor%}
          {%endif%}
          <div class="mt-12 flex flex-col items-center" style="margin-top: 3rem;">
            <h1 class="text-2xl xl:text-3xl font-extrabold" style="size: 10px;">
              Sign up
            </h1>
            <div class="w-full flex-1 mt-8">


              <div class="my-12 border-b text-center" style="margin-top: 0rem;">
                <div
                  class="leading-none px-2 inline-block text-sm text-gray-600 tracking-wide font-medium bg-white transform translate-y-1/2"
                >
                  sign up with e-mail
                </div>
              </div>
              <div class="mx-auto max-w-xs">


                <form action="" method="POST">
                  {% csrf_token %}

                    <input
                      class="w-full px-8 py-3 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white"
                      type="email"
                      name="user-email"
                      placeholder="Email"
                      required/>
                    <input pattern="^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$"
                      class="w-full px-8 py-3 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white mt-5"
                      id="password" type="password" name="user-password1" placeholder="Password" title="Your password must be at least 8 characters long, contain at least one number and have a mixture of uppercase and lowercase letters including special character (@!%*#?&)."
                      required/>

                    <input
                      class="w-full px-8 py-3 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white mt-5"
                      type="password" id="confirm-password" name="user-password2" placeholder="Confirm Password"
                      required/>
                    <button
                      class=" mt-5 tracking-wide font-semibold bg-indigo-500 text-gray-100 w-full py-3 rounded-lg hover:bg-indigo-700 transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none"
                    >
                    {{form.errors}}
                    <svg
                      class="w-6 h-6 -ml-2"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path d="M16 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" />
                      <circle cx="8.5" cy="7" r="4" />
                      <path d="M20 8v6M23 11h-6" />
                    </svg>
                    <span class="ml-3">
                      Sign Up
                    </span>
                  </button>
                </form>


                <hr>
                <br>
                <hr style="width: 100%; height: 2px; background-color: black;">
                <br>

                <a href="{% url 'users:login' %}"> Login </a>

                <p class="mt-6 text-xs text-gray-600 text-center">
                  I agree to abide by templatana's
                  <a href="#" class="border-b border-gray-500 border-dotted">
                    Terms of Service
                  </a>
                  and its
                  <a href="#" class="border-b border-gray-500 border-dotted">
                    Privacy Policy
                  </a>
                </p>

              </div>
            </div>
          </div>
        </div>


        <div class="flex-1 bg-indigo-100 text-center hidden lg:flex">
          <div
            class="m-12 xl:m-16 w-full bg-contain bg-center bg-no-repeat"
            style="background-image: url('https://storage.googleapis.com/devitary-image-host.appspot.com/15848031292911696601-undraw_designer_life_w96d.svg');"
          ></div>
        </div>
      </div>


      <script>
        console.log("hello")
        var password = document.getElementById("password")
        confirm_password = document.getElementById("confirm-password");

        function validatePassword(){
        if(password.value != confirm_password.value) {
            confirm_password.setCustomValidity("Passwords Don't Match");
        } else {
            confirm_password.setCustomValidity('');
        }
        }

        password.onchange = validatePassword;
        confirm_password.onkeyup = validatePassword;


      </script>


{% endblock %}